# Render Blueprint for deploying React + Express app
services:
  - type: web
    name: portfolio-app
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: OAUTH_REDIRECT_URI
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: RAPIDAPI_KEY
        sync: false
      - key: ZERODHA_API_KEY
        sync: false
